### ISSUE TITLE
Can I use your username?

### ISSUE THREAD

**Issue by yuzumx** [remx/test#1]
Your username has a special meaning to me.
If possible, I want to use your username, and are willing to pay.

Thanks

**Comment by remx** [comment]
How can I give it for you?

**Comment by yuzumx** [comment]
Thank you very much! ... you just need to rename your username ...

Your avatar --> Settings --> Account

![1](https://user-images.githubusercontent.com/26828933/36595187-2f4b3abc-18dc-11e8-96fc-9fbdbf62558c.jpg)

Do I need to pay for it?

I can not see your private repo. So this may bother you.

I mention this reckless request because your account does not seem to have much repo.

I am sorry if it affects you.

**Comment by yuzumx** [comment]
Forget ... you do not need to do anything.

Because I found this username (remx) is occupied in anywhere, so I chose to be unified into my current user name.

Thank you again!
